import {
  Activity,
  BookOpen,
  CalendarCheck2,
  GraduationCap,
  LayoutDashboard,
  ListChecks,
  School,
  ShieldCheck,
  Stars,
  UserCog,
  UsersRound,
  ClipboardList,
  ChartNoAxesCombined,
  PlusCircle,
  SquareActivity,
} from "lucide-react";
import type { NavigationItem, SearchSuggestion } from "./types";

export const MAIN_NAVIGATION: NavigationItem[] = [
  { label: "Ringkasan", href: "/dashboard", icon: LayoutDashboard },
  {
    label: "Institusi",
    href: "/institutions",
    icon: School,
    roles: ["super_admin", "dinas", "dinas_pendidikan"],
  },
  {
    label: "Pengguna",
    href: "/users?category=staff",
    icon: UsersRound,
    children: [
      { label: "Guru & Admin", href: "/users?category=staff", icon: UserCog },
      { label: "Siswa", href: "/users?category=student", icon: GraduationCap },
    ],
  },
  { label: "Grup Pembelajaran", href: "/learning-groups", icon: Stars },
  { label: "Materi Belajar", href: "/learning-resources", icon: BookOpen },
];

export const INSIGHT_NAVIGATION: NavigationItem[] = [
  {
    label: "Absensi",
    href: "/attendances?category=teacher",
    icon: CalendarCheck2,
    children: [
      { label: "Guru", href: "/attendances?category=teacher", icon: UserCog },
      {
        label: "Siswa",
        href: "/attendances?category=student",
        icon: GraduationCap,
      },
    ],
  },
  {
    label: "Aktivitas",
    href: "/activities",
    icon: Activity,
    children: [
      {
        label: "Jenis Aktivitas",
        href: "/activity-items",
        icon: ClipboardList,
      },
      { label: "Catatan Aktivitas", href: "/activities", icon: SquareActivity },
    ],
  },
  {
    label: "Kuis",
    href: "/quizzes",
    icon: ListChecks,
    children: [
      { label: "Daftar Kuis", href: "/quizzes", icon: ListChecks },
      {
        label: "Riwayat Sesi & Nilai",
        href: "/quiz-sessions",
        icon: ClipboardList,
      },
    ],
  },
  {
    label: "Role & Izin",
    href: "/roles",
    icon: ShieldCheck,
    roles: ["super_admin"],
  },
];

export const SEARCH_SUGGESTIONS: SearchSuggestion[] = [
  {
    label: "Tambah Institusi",
    description: "Buat institusi atau sekolah baru.",
    category: "Tambah data",
    href: "/institutions/create",
    keywords: ["tambah", "buat", "institusi", "sekolah"],
    icon: PlusCircle,
    tone: "blue",
  },
  {
    label: "Tambah Role",
    description: "Buat role dan izin baru.",
    category: "Tambah data",
    href: "/roles/create",
    keywords: ["tambah", "buat", "role", "izin", "permission"],
    icon: PlusCircle,
    tone: "violet",
  },
  {
    label: "Tambah Grup belajar",
    description: "Buat kelas atau grup belajar baru.",
    category: "Tambah data",
    href: "/learning-groups/create",
    keywords: ["tambah", "buat", "grup", "kelas", "belajar"],
    icon: PlusCircle,
    tone: "blue",
  },
  {
    label: "Tambah Anggota grup",
    description: "Tambahkan anggota ke grup belajar.",
    category: "Tambah data",
    href: "/learning-group-members/create",
    keywords: ["tambah", "buat", "anggota", "grup"],
    icon: PlusCircle,
    tone: "violet",
  },
  {
    label: "Tambah Guru & Admin",
    description: "Buat akun guru, admin, atau staf baru.",
    category: "Tambah data",
    href: "/users/create?category=staff",
    keywords: ["tambah", "buat", "guru", "admin", "staf", "pengguna"],
    icon: PlusCircle,
    tone: "blue",
  },
  {
    label: "Tambah Siswa",
    description: "Buat akun siswa baru.",
    category: "Tambah data",
    href: "/users/create?category=student",
    keywords: ["tambah", "buat", "siswa", "murid", "student", "pengguna"],
    icon: PlusCircle,
    tone: "violet",
  },
  {
    label: "Tambah Materi belajar",
    description: "Buat materi atau sumber pembelajaran baru.",
    category: "Tambah data",
    href: "/learning-resources/create",
    keywords: ["tambah", "buat", "materi", "resource", "pembelajaran"],
    icon: PlusCircle,
    tone: "emerald",
  },
  {
    label: "Tambah Kuis",
    description: "Buat kuis pembelajaran baru.",
    category: "Tambah data",
    href: "/quizzes/create",
    keywords: ["tambah", "buat", "kuis", "quiz", "soal"],
    icon: PlusCircle,
    tone: "orange",
  },
  {
    label: "Tambah Sesi kuis",
    description: "Buat sesi pelaksanaan kuis.",
    category: "Tambah data",
    href: "/quiz-sessions/create",
    keywords: ["tambah", "buat", "sesi", "kuis", "quiz"],
    icon: PlusCircle,
    tone: "orange",
  },
  {
    label: "Tambah Absensi",
    description: "Catat kehadiran atau ketidakhadiran.",
    category: "Tambah data",
    href: "/attendances/create",
    keywords: ["tambah", "buat", "absensi", "kehadiran"],
    icon: PlusCircle,
    tone: "blue",
  },
  {
    label: "Tambah Alasan ketidakhadiran",
    description: "Buat alasan izin atau ketidakhadiran.",
    category: "Tambah data",
    href: "/absence-reasons/create",
    keywords: ["tambah", "buat", "alasan", "izin", "ketidakhadiran"],
    icon: PlusCircle,
    tone: "violet",
  },
  {
    label: "Tambah Aktivitas",
    description: "Catat aktivitas positif atau pelanggaran.",
    category: "Tambah data",
    href: "/activities/create",
    keywords: ["tambah", "buat", "aktivitas", "poin"],
    icon: PlusCircle,
    tone: "blue",
  },
  {
    label: "Tambah Jenis aktivitas",
    description: "Buat jenis aktivitas dan poinnya.",
    category: "Tambah data",
    href: "/activity-items/create",
    keywords: ["tambah", "buat", "jenis", "aktivitas", "poin"],
    icon: PlusCircle,
    tone: "emerald",
  },
  {
    label: "Tambah Kategori aktivitas",
    description: "Buat kategori aktivitas baru.",
    category: "Tambah data",
    href: "/activity-categories/create",
    keywords: ["tambah", "buat", "kategori", "aktivitas"],
    icon: PlusCircle,
    tone: "violet",
  },
  {
    label: "Grafik Aktivitas",
    description: "Pantau tren aktivitas positif dan pelanggaran siswa.",
    category: "Aktivitas",
    href: "/activities/chart",
    keywords: [
      "grafik",
      "chart",
      "laporan",
      "aktivitas",
      "positif",
      "pelanggaran",
      "violation",
    ],
    icon: ChartNoAxesCombined,
    tone: "blue",
  },
  {
    label: "Laporan absensi",
    description: "Lihat rekap kehadiran dan keterlambatan",
    category: "Laporan",
    href: "/attendances",
    keywords: ["absen", "absensi", "hadir", "kehadiran", "terlambat"],
    icon: CalendarCheck2,
    tone: "blue",
  },
  {
    label: "Guru & admin",
    description: "Cari dan kelola guru, admin, dan staf",
    category: "Pengguna",
    href: "/users?category=staff",
    keywords: ["user", "pengguna", "guru", "teacher", "admin", "staf"],
    icon: UserCog,
    tone: "violet",
  },
  {
    label: "Data siswa",
    description: "Cari dan kelola seluruh siswa",
    category: "Pengguna",
    href: "/users?category=student",
    keywords: ["user", "pengguna", "siswa", "student", "murid", "buat siswa"],
    icon: GraduationCap,
    tone: "blue",
  },
  {
    label: "Materi pembelajaran",
    description: "Kelola sumber belajar dan materi kelas",
    category: "Pembelajaran",
    href: "/learning-resources",
    keywords: ["materi", "modul", "resource", "bahan ajar"],
    icon: BookOpen,
    tone: "emerald",
  },
  {
    label: "Kuis pembelajaran",
    description: "Kelola kuis dan soal untuk siswa",
    category: "Pembelajaran",
    href: "/quizzes",
    keywords: ["kuis", "quiz", "soal", "ujian"],
    icon: ListChecks,
    tone: "orange",
  },
  {
    label: "Aktivitas siswa",
    description: "Buka catatan aktivitas dan poin",
    category: "Aktivitas",
    href: "/activities",
    keywords: ["aktivitas", "poin", "pelanggaran"],
    icon: Activity,
    tone: "blue",
  },
];
